spring:
  datasource:
#    driver-class-name: "org.h2.Driver"
#    url: "jdbc:h2:mem:dev_db"
#    username: "sa"
#    password: "sa"
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5432/testdb
    username: user
    password: password
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.security.web: DEBUG
