spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: ${SPRING_DATASOURCE_URL} #jdbc:postgresql://localhost:5432/testdb
    username: ${SPRING_DATASOURCE_USERNAME} #user
    password: ${SPRING_DATASOURCE_PASSWORD} #password
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update #create-drop
    show-sql: true
    generate-ddl: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.security.web: DEBUG
