version: '2'

services:
  app:
    image: 'tech-mbti'
    container_name: 'tech-mbti-container'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/testdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

#  postgres:
#    image: 'postgres:14.2'
#    container_name: 'postgres-container'
#    restart: unless-stopped
#    volumes:
#      - db-data:/data/db
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=testdb